
services:
  backend:
    build: ./Backend
    container_name: studypilot-backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env

  frontend:
    build:
      context: ./Frontend
      args:
        VITE_API_URL: http://localhost:5000
    container_name: studypilot-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
